### ISSUE TITLE
Compilation error for non Vuetify apps

### ISSUE THREAD

**Issue by mikerockett** [yariksav/vue-google-places#3]
The recent commit (https://github.com/yariksav/vue-google-places/commit/f337054ad39c6c59d0bd6a621257d078ac5eb804) to add Vuetify support is now causing our build process for a non Vuetify app to throw an error:

```
This dependency was not found:
* vuetify/lib in ./node_modules/vue-google-places/dist/vue-google-places.esm.js
```

Will roll back for now, but please can this be made optional?

Thanks! 😀

**Comment by Speedy059** [comment]
I had the same issue. I'm using the non-vuetify version and it now requires vuetify/lib. I had to roll back to 0.1.5, 0.1.6 breaks it.

**Comment by yariksav** [comment]
Hi! If you are using typescript, you have to add vuetify to tsconfig compiler types. See comment
https://github.com/vuetifyjs/vuetify/issues/3943#issuecomment-414551981

**Comment by mikerockett** [comment]
Our project isn't using TS – any other way around this? If not, I'm happy to extract the package and include it directly within the project.

**Comment by Speedy059** [comment]
Same, we aren't using typescript with VueJS until 3.x is released.

**Comment by lelesrc** [comment]
up!

**Comment by balakan** [comment]
Yap!
had to roll back to 0.1.5.

**Comment by jamesofficer** [comment]
Definitely still an issue. Also rolled back to an earlier version to fix.

**Comment by kasperkamperman** [comment]
Same problem here.

**Comment by zagreusinoz** [comment]
2021 still an issue.  Is this project abandoned?

**Comment by MAvalleza** [comment]
This is still persisting unfortunately

**Comment by mikerockett** [comment]
This project doesn't appear to be maintained anymore. Closing issue.
